version: "3"
services:
  mongo_master:
    image: mongo
    ports:
      - 27018:27017
    restart: unless-stopped
    volumes:
     - ./data/db:/data/db
    command: mongod --replSet rs0
  
  mongo_slave_1:
    image: mongo
    ports:
      - 27019:27017
    restart: unless-stopped
    command: mongod --replSet rs0

  mongo-init-replica:
    image: mongo
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo mongo_master/live_streaming_db --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ 
                { _id: 0, host: 'localhost:27018' },
                { _id: 1, host: 'localhost:27019' }
              ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo_master
      - mongo_slave_1
    